language: python
python:
  - 3.5
install:
  - pip install coveralls
script:
  - python setup.py test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: davis.kirkendall
  password:
    secure: "eU2z09yzxHW6VLrLZRQjImVprQQqgfo+e7BHTdts8GIJWaUwe3QNvhiqbi+QZ7POO5NFAUr4xh34IyORfKqyTPkjW3l5ZppfcerRipVOGazPQvxKKvQq4wI6kj0AOBFwyhgJuEAXrC99AbPZNfSbAo6oGmN3qI2jywPEYFKlW6xiXpxGyNla5e6Lslj9pC6owzKt4dTHoljiPMk0J+HKP7KiuR3swwmRh4gCzv6b3h7PmkqaXbXWRsIRZqtN9i/zhoYc5Jlmtv6KdhXQnf/ErOcZwmPM9qWcKaGmotpiTLT4Ia+92s9EHuPcXeX81D0RUaV8bwBo4arZhfInXhNKigOjg6WKxa2NPwYq2Lp0Pivb+FfY2an/bHxgTkGrtfZVu4QkMl/anfkYBzAl5Uvp9guGUDd09wmA7aB0JmCqXmFzS11dVIq7BH3HZFwOujw/cmmkbu4Ce3YuCj8JbITLLfcGUaoerVLxKcU+EjGWByLUuMxk0geYVJPaPAuaA2SIWWNzVoO71x0312l/wKi1ZdJwNbIFzMd9wKhp9Hg61OtGVaI5SetwyZZag23L0pIGZomIZEhxpGCDg27A+HdW7Kcb8HfjQ7exuXHmblkZQ8Q76VQtwZ9LKbBPll2CoyQnn8JzSb0UrupsgsO8KE1sIadjwudUuA/MKKcI6iYFJVI="
  on:
    tags: true
    branch: master
